name: Build Deb Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: igorfreire/gnuradio-oot-dev:3.10.7.0-ubuntu-jammy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Workaround for unsafe repo git error
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Check CMakeLists version matches tag
        run: .packaging/scripts/check-version-tag.sh $GITHUB_REF_NAME
      - name: Install debian build dependencies
        run: |
          apt update && apt install -y \
            debhelper \
            devscripts \
            dh-python
      - name: Install gr-dvbs2rx build dependencies
        run: |
          apt update && apt install -y \
            libsndfile1-dev
      - name: Build deb package
        run: .packaging/scripts/pkg-debian.sh
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Deb Packages
          path: .packaging/build/**/*.deb
