name: Build Deb Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install debuild dependencies
      run: |
        apt update && \
          DEBIAN_FRONTEND="noninteractive" apt install -y \
            debhelper \
            devscripts \
            dh-python \
            git \
            software-properties-common
    - name: Install gr-dvbs2rx build dependencies
      run: |
        add-apt-repository -y ppa:gnuradio/gnuradio-releases && \
        DEBIAN_FRONTEND="noninteractive" apt install -y \
          cmake \
          doxygen \
          gnuradio-dev \
          graphviz \
          libsndfile1-dev \
          libspdlog-dev \
          pkg-config \
          pybind11-dev
    - name: Build deb package
      run: .packaging/scripts/pkg-debian.sh
