name: Build RPM Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["fedora:38", "fedora:39"]
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Install git
        run: |
          dnf install -y git
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Workaround for unsafe repo git error
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Check CMakeLists version matches target release
        run: .packaging/scripts/check-version-tag.sh ${{ github.event.inputs.release || github.ref_name }}
      - name: Install rpmbuild dependencies
        run: |
          dnf install -y \
            coreutils \
            dnf-utils \
            rpm-build \
            rpm-devel \
            rpmdevtools \
            rpmlint
      - name: Install gr-dvbs2rx build dependencies
        run: |
          dnf install -y \
            doxygen \
            fftw-devel \
            g++ \
            git \
            gmp-devel \
            gnuradio-devel \
            graphviz \
            libsndfile-devel \
            pybind11-devel \
            spdlog-devel
      - name: Build RPM package
        run: .packaging/scripts/pkg-rpm.sh
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: RPM Packages
          path: ~/rpmbuild/RPMS/**/*.rpm
